"use client";

import React, { useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import { useTokenAndRole } from "@/app/containers/utils/session/CheckSession";
import Navbar from "@/app/components/navbar/navbar";
import { Typography, CircularProgress, Divider, Paper } from "@mui/material";

interface Item {
  productId: string;
  name: string;
  obsBrandGoodId?: string;
  coohomId?: string;
  workGroup?: string;
  workTask?: string;
  quantity?: number;
  targetDays?: number;
  bufferDays?: number;
  poDays?: number;
}

interface POData {
  poNumber: string;
  generatedBy: string;
  generatedAt: string;
  items: Item[];
  totalAmount: number;
  merchantDetails: {
    businessName: string;
    address: string;
    contactInfo: string;
  };
  workOrderDetails: {
    workOrderId: string;
    customerName: string;
    projectName: string;
    expectedStartDate: string;
    expectedCompletionDate: string;
  };
  metadata: {
    generatedBy: string;
    generatedAt: string;
    version: string;
  };
}

const PODataPage = () => {
  const searchParams = useSearchParams();
  const { token } = useTokenAndRole();

  const workOrderId = searchParams.get("workOrderId");
  const productId = searchParams.get("productId");

  const [poData, setPoData] = useState<POData | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!workOrderId || !productId) return;

    const fetchPOData = async () => {
      setLoading(true);
      setError(null);
      try {
        const res = await fetch(
          `${process.env.NEXT_PUBLIC_API_URL}/work-orders/${workOrderId}/products/${productId}/po-data`,
          { headers: { Authorization: `Bearer ${token}` } }
        );

        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        const data = await res.json();
        setPoData(data);
      } catch (err: any) {
        setError(err.message || "Something went wrong");
      } finally {
        setLoading(false);
      }
    };

    fetchPOData();
  }, [workOrderId, productId, token]);

  if (!workOrderId || !productId)
    return (
      <div className="p-4 text-red-600">
        Please provide workOrderId and productId in query params.
      </div>
    );

  if (loading)
    return (
      <div className="flex justify-center items-center h-64">
        <CircularProgress />
      </div>
    );

  if (error)
    return <div className="p-4 text-red-600 font-semibold">Error: {error}</div>;

  return (
    <>
      <Navbar label="PO Data" />
      <div className="min-h-screen p-6  bg-gray-50">
        <Paper elevation={4} className="p-6 space-y-6">
          <Typography variant="h4" className="font-bold mb-4">
            Purchase Order Details
          </Typography>

          {poData ? (
            <>
              {/* PO Information */}
              <section>
                <Typography variant="h6" className="mb-2 font-semibold">
                  PO Information
                </Typography>
                <p>
                  <b>PO Number:</b> {poData.poNumber}
                </p>
                <p>
                  <b>Generated By:</b> {poData.generatedBy}
                </p>
                <p>
                  <b>Generated At:</b>{" "}
                  {new Date(poData.generatedAt).toLocaleString()}
                </p>
                <Divider className="my-3" />
                <p>
                  <b>Total Amount:</b> ₹{poData.totalAmount}
                </p>
              </section>

              <Divider />

              {/* Merchant Details */}
              <section>
                <Typography variant="h6" className="mb-2 font-semibold">
                  Merchant Details
                </Typography>
                <p>
                  <b>Business Name:</b> {poData.merchantDetails.businessName}
                </p>
                <p>
                  <b>Address:</b> {poData.merchantDetails.address}
                </p>
                <p>
                  <b>Contact Info:</b> {poData.merchantDetails.contactInfo}
                </p>
              </section>

              <Divider />

              {/* Work Order Details */}
              <section>
                <Typography variant="h6" className="mb-2 font-semibold">
                  Work Order Details
                </Typography>
                <p>
                  <b>Work Order ID:</b> {poData.workOrderDetails.workOrderId}
                </p>
                <p>
                  <b>Customer Name:</b> {poData.workOrderDetails.customerName}
                </p>
                <p>
                  <b>Project Name:</b> {poData.workOrderDetails.projectName}
                </p>
                <p>
                  <b>Expected Start:</b>{" "}
                  {new Date(
                    poData.workOrderDetails.expectedStartDate
                  ).toLocaleDateString()}
                </p>
                <p>
                  <b>Expected Completion:</b>{" "}
                  {new Date(
                    poData.workOrderDetails.expectedCompletionDate
                  ).toLocaleDateString()}
                </p>
              </section>

              <Divider />

              {/* Items Table */}
              <section className="overflow-x-auto">
                <Typography variant="h6" className="mb-2 font-semibold">
                  Items
                </Typography>
                {poData.items && poData.items.length > 0 ? (
                  <table className="w-full text-left border border-gray-200">
                    <thead className="bg-gray-100">
                      <tr>
                        <th className="px-3 py-2 border">Product</th>
                        <th className="px-3 py-2 border">Work Group</th>
                        <th className="px-3 py-2 border">Work Task</th>
                        <th className="px-3 py-2 border">Quantity</th>
                        <th className="px-3 py-2 border">Target Days</th>
                        <th className="px-3 py-2 border">Buffer Days</th>
                        <th className="px-3 py-2 border">PO Days</th>
                      </tr>
                    </thead>
                    <tbody>
                      {poData.items.map((item, i) => (
                        <tr key={i} className="hover:bg-gray-50">
                          <td className="px-3 py-2 border">{item.name}</td>
                          <td className="px-3 py-2 border">
                            {item.workGroup || "-"}
                          </td>
                          <td className="px-3 py-2 border">
                            {item.workTask || "-"}
                          </td>
                          <td className="px-3 py-2 border">
                            {item.quantity ?? "-"}
                          </td>
                          <td className="px-3 py-2 border">
                            {item.targetDays ?? "-"}
                          </td>
                          <td className="px-3 py-2 border">
                            {item.bufferDays ?? "-"}
                          </td>
                          <td className="px-3 py-2 border">
                            {item.poDays ?? "-"}
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                ) : (
                  <div className="text-gray-500">No items available.</div>
                )}
              </section>

              <Divider />

              {/* Metadata */}
              <section>
                <Typography variant="h6" className="mb-2 font-semibold">
                  Metadata
                </Typography>
                <p>
                  <b>Generated By:</b> {poData.metadata.generatedBy}
                </p>
                <p>
                  <b>Generated At:</b>{" "}
                  {new Date(poData.metadata.generatedAt).toLocaleString()}
                </p>
              </section>
            </>
          ) : (
            <div className="text-gray-600">No PO data found.</div>
          )}
        </Paper>
      </div>
    </>
  );
};

export default PODataPage;
